#!/usr/bin/env bash

BAT_NUMBER=${BLOCK_INSTANCE:-0}
ACPI=$(acpi -b | grep "Battery $BAT_NUMBER")

STATUS=$(echo $ACPI | awk '{ gsub(/,/,""); print $3 }')
PERCENT=$(echo $ACPI | awk '{ gsub(/,/,""); print $4 }' | tr -d %)
REMAIN="$(echo $ACPI | sed -rn 's/.* ([0-9]+:[0-9]+).*/\1/gp')"

[[ -n "${REMAIN}" ]] && REMAIN="(${REMAIN})"

if [ $STATUS == 'Discharging' ]; then
  if [ $PERCENT -lt 5 ]; then
    exit 33
  elif [ $PERCENT -lt 20 ]; then
    ICON=""
  elif [ $PERCENT -lt 40 ]; then
    ICON=""
  elif [ $PERCENT -lt 60 ]; then
    ICON=""
  elif [ $PERCENT -lt 85 ]; then
    ICON=""
  else
    ICON=""
  fi
elif [ $STATUS == 'Charging' ]; then
  ICON=""
else
  ICON=""
fi

echo "<span color='#868686' size='large'>$ICON</span><span> $PERCENT%$REMAIN</span>";
