#!/usr/bin/env bash

LAYOUT=$(setxkbmap -query | awk '
    BEGIN{layout="";variant=""}
    /^layout/{layout=$2}
    /^variant/{variant=" ("$2")"}
  END{printf("%s%s",layout,variant)}')

echo "<span color='#868686'></span><span> $LAYOUT</span>"
