# zmodload zsh/zprof

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Theme
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="lambda"

# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Add wisely, as too many plugins slow down shell startup.
plugins=(vi-mode git autojump tmux fzf)

# Aliases
alias v="nvim"
alias clj='clojure'
alias vimdiff='nvim -d'

# Exports
export EDITOR=nvim          # Set Nvim as default editor
export GPG_TTY=$(tty)       # Set GPG TTY
export TERM="tmux-256color" # Set tmux as colors scheme

# History
setopt BANG_HIST                 # Treat the '!' character specially during expansion.
setopt EXTENDED_HISTORY          # Write the history file in the ":start:elapsed;command" format.
setopt INC_APPEND_HISTORY        # Write to the history file immediately, not when the shell exits.
setopt SHARE_HISTORY             # Share history between all sessions.
setopt HIST_EXPIRE_DUPS_FIRST    # Expire duplicate entries first when trimming history.
setopt HIST_IGNORE_DUPS          # Don't record an entry that was just recorded again.
setopt HIST_IGNORE_ALL_DUPS      # Delete old recorded entry if new entry is a duplicate.
setopt HIST_FIND_NO_DUPS         # Do not display a line previously found.
setopt HIST_IGNORE_SPACE         # Don't record an entry starting with a space.
setopt HIST_SAVE_NO_DUPS         # Don't write duplicate entries in the history file.
setopt HIST_REDUCE_BLANKS        # Remove superfluous blanks before recording entry.
setopt HIST_VERIFY               # Don't execute immediately upon history expansion.
setopt HIST_BEEP                 # Beep when accessing nonexistent history.

HISTSIZE=10000000                # history size
SAVEHIST=10000000                # history save size
DISABLE_AUTO_TITLE="true"        # avoid window rename
KEYTIMEOUT=1                     # remove delay

# Zsh init
source $ZSH/oh-my-zsh.sh

# PATH adds
PATH="$HOME/.local/bin:/usr/local/bin":$PATH

# work specific configs (git ignored)
[ -f ~/.workrc ] && source ~/.workrc

# java home
export JAVA_HOME=/usr/lib/jvm/default
export GRAALVM_HOME=/usr/lib/jvm/java-11-graalvm

# dotnet home
DOTNET_CLI_TELEMETRY_OPTOUT=1 # opt-out of telemetry

# arch zsh-autosuggestions
[ -f /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh ] && source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh

# zprof
