# Minimalist picom (new compton) config for solving screen tearing problems.

# Specify the backend to use: `xrender`, `glx`, `egl` or `xr_glx_hybrid`.
# `xrender` is the default one.
backend = "glx";

# Enable/disable VSync.
vsync = true;

# Sets the radius of rounded window corners. When > 0, the compositor will
# round the corners of windows. Does not interact well with
# `transparent-clipping`.
corner-radius = 5
round-borders = 5;

round-borders-rule = [ "8:class_g = 'i3bar'" ];
corner-radius-rules = [ "8:class_g = 'i3bar'" ];

# Exclude conditions for rounded corners.
rounded-corners-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'",
  "class_g = 'Vmware-view'"
];
